---
meta:
  name:    cf-plugin-open
  release: cf-plugin-open
  target:  sw
  url:     https://ci.starkandwayne.com

  initial_version: 1.2.0

  shipit:
    targets: "linux/amd64 darwin/amd64 windows/amd64"

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  cloudfoundry-community
    repo:   cf-plugin-open
    private_key:  (( vault "secret/pipelines/shared/github:private_key" ))
    access_token: (( vault "secret/pipelines/shared/github:access_token" ))

  slack:
    webhook: unknown
    channel: '#vault'
