---
meta:
  name:    cf-plugin-open
  release: cf-plugin-open
  target:  sw
  url:     https://ci.starkandwayne.com

  initial_version: 1.2.0

  shipit:
    targets: "linux/amd64 darwin/amd64 windows/amd64"

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  cloudfoundry-community
    repo:   cf-plugin-open
    private_key:  (( vault "secret/pipelines/shared/github:private_key" ))
    access_token: (( vault "secret/pipelines/shared/github:access_token" ))

  slack:
    webhook: unknown
    channel: '#vault'

groups:
  - name: (( grab meta.pipeline ))
    jobs:
      - ((append))
      - publish-plugin

jobs:
  - name: publish-plugin
    public: false
    serial: true
    plan:
      - do:
        - name: inputs
          aggregate:
            - { get: git }
            # - { get: git,     passed: [shipit] }
            - { get: version, passed: [shipit] }
            - { get: github,  passed: [shipit] }
            - { get: cli-plugin-repo }
        - name: update-cli-plugin-repo
          task: update-cli-plugin-repo
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: (( grab meta.image.name ))
                tag:        (( grab meta.image.tag ))
            inputs:
              - name: git
              - name: version
              - name: github
              - name: cli-plugin-repo
            outputs:
              - name: pullrequest-repo
            run:
              path: git/ci/scripts/update-cli-plugin-repo
              args: []
            params: {}
        - name: cli-plugin-repo-pullrequests
          put: cli-plugin-repo-pullrequests
          params:
            repository: pullrequest-repo
            force: true
        - name: submit-pull-request
          task: submit-pull-request
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: (( grab meta.image.name ))
                tag:        (( grab meta.image.tag ))
            inputs:
              - name: git
              - name: version
            run:
              path: git/ci/scripts/submit-pull-request
              args: []
            params:
              BASE_ORG_REPO: cloudfoundry-incubator/cli-plugin-repo
              BASE_BRANCH: master
              PR_ORG: starkandwayne
              PR_BRANCH: (( concat meta.name "-release" ))
              GITHUB_TOKEN: (( grab meta.github.access_token ))

resources:
  - name: cli-plugin-repo
    type: git
    source:
      uri:    https://github.com/cloudfoundry-incubator/cli-plugin-repo
      branch: master

  - name: cli-plugin-repo-pullrequests
    type: git
    source:
      uri:    git@github.com:starkandwayne/cf-cli-plugin-repo.git
      branch: (( concat meta.name "-release" ))
      private_key: (( grab meta.github.private_key ))
