---
meta:
  name:    cf-plugin-open
  release: cf-plugin-open
  target:  ohio-cf
  url:     https://ci2.starkandwayne.com

  initial_version: 1.2.0

  shipit:
    targets: "linux/amd64 darwin/amd64 windows/amd64"

  aws:
    access_key: ((aws-cfcommunity-access))
    secret_key: ((aws-cfcommunity-secret))

  github:
    owner:  cloudfoundry-community
    repo:   cf-plugin-open
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook: unknown
    channel: '#vault'
